
platform :ios, '8.0'


source 'https://github.com/CocoaPods/Specs.git'

target 'LoginModule' do
    
    pod 'MTRouter'
    pod 'MTTheme'
    pod 'CommonModule', :path => '../../System_Module/CommonModule'


    pod 'Masonry'
    pod 'SDWebImage'
    pod 'SVProgressHUD'
    
end

